package com.keithmackay.systemtool.settings;

public class Settings {
	public static final String VERSION = "SETTINGS.VERSION", CLIPBOARD_HISTORY = "SETTINGS.CLIPBOARD_HISTORY";
	public static final String BACKGROUND_PROCESS_RUNNING = "SETTINGS.BACKGROUND_PROCESS_RUNNING", WORKSPACE_MONITOR_RUNNING = "SETTINGS.WORKSPACE_MONITOR_RUNNING";
}
